---
title: "Project 3 Exploration"
author: "Tejit Pabari"
date: "4/10/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	class.source="bg-success",
	class.output="bg-warning"
)

library(ggplot2)
library(scales)
library(glmnet)
library(jsonlite)
library(superml)
library(tidytext)
library(text2vec)
library(dplyr)
library(forcats)
library(stopwords)
library(clue)
library(cluster)
library(factoextra)
library(readtext)
library(tokenizers)
library(pdist)
library(readr)
library(stringr)
require(reshape2)
setwd("/Users/tejitpabari/Desktop/DataMining/Projects/3")
gg_global_theme <- theme(axis.text=element_text(size=16), 
                         axis.title=element_text(size=16),
                         title=element_text(size=16))
# rm(list = ls())
```

### Load data
```{r}
genius_data <- read_csv("data/genuis_data.csv")
info_cols <- c("key", "song", "artist", "album_name")
ranking_cols <- sapply((2006:2020), function(x) paste0("song_ranking_",x))
feature_cols <- names(genius_data)[13:23]
# feature_cols <- feature_cols[! feature_cols %in% c("song_loudness","song_key")]
feature_cols2 <- c(feature_cols,"song_popularity", "song_duration", "song_lyric_valence", "song_lyrics_repetitiveness")
genius_data$max_ranking <- apply(genius_data[,ranking_cols], 1, max)
genius_data$max_ranking_year <- sapply(ranking_cols[apply(genius_data[,ranking_cols], 1, which.max)], function(x) as.numeric(strsplit(x,"_")[[1]][3]))
genius_data$ranking_duration <- apply(genius_data[,ranking_cols], 1, function(x) length(x[x!=0]))
ranking_info_cols = c("max_ranking","max_ranking_year","ranking_duration")
genius_data$ranking_3 <- sapply(genius_data$max_ranking, function(x){
  if(x<=10){return(1)}
  if(x<=50){return(2)}
  return(3)
})
```

```{r}
names(genius_data)
head(genius_data)[,info_cols]
head(genius_data)[,ranking_cols]
head(genius_data)[,ranking_info_cols]
```


## Data exploration
```{r}
dim(genius_data)
```

### Albums
#### Album total tracks
```{r}
ggplot(data = genius_data, aes(x=album_total_tracks)) +
  geom_histogram() + 
  ggtitle("Album total tracks") + xlab("Tracks") + ylab("Number of Albums")
```

Looking at exceptions (total tracks > 25)
```{r}
temp <- genius_data[genius_data$album_total_tracks>25,
            c(info_cols,"album_total_tracks")]
```
```{r eval=FALSE, echo=FALSE}
View(temp[order(temp$album_total_tracks,decreasing = TRUE),])
```
```{r}
dim(temp)
head(temp[order(temp$album_total_tracks,decreasing = TRUE),], n=2)
```

#### Album Popularity
```{r}
ggplot(data = genius_data, aes(x=album_popularity)) +
  geom_histogram() + 
  ggtitle("Album Popularity") + xlab("Popularity") + ylab("Number of Albums")
```

### Song
#### Song rankings
```{r}
ggplot(data = genius_data, aes(x=max_ranking)) +
  geom_histogram(bins = 100) +
  ggtitle("Song Rankings") + xlab("Ranking") + ylab("Number of Songs") + gg_global_theme
ggsave('images/stats/max_ranking.png')
```

#### Song rankings 3
```{r}
ggplot(data = as.data.frame(table(genius_data$ranking_3)), aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity") + ggtitle("Song Rankings 3") + xlab("Ranking") + ylab("Number of Songs") + gg_global_theme
ggsave('images/stats/ranking_3.png')
```

#### Song duration
```{r}
ggplot(data = genius_data, aes(x=song_duration/60000)) +
  geom_histogram() + 
  ggtitle("Song Duration (minutes)") + xlab("Duration") + ylab("Number of Songs") 
ggsave('images/stats/song_duration.png')
```

Checking exceptions (duration > 6 minutes)
```{r}
temp <- genius_data[genius_data$song_duration>(6*60000),
            c(info_cols,"song_duration")]
temp$song_duration_minutes <- temp$song_duration/60000
```

```{r eval=FALSE, echo=FALSE}
View(temp[order(temp$song_duration,decreasing = TRUE),])
```
```{r}
dim(temp)
head(temp[order(temp$song_duration,decreasing = TRUE),], n=2)
```

#### Song explicit
```{r}
ggplot(data = as.data.frame(table(genius_data$song_explicit)), aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity") + ggtitle("Song Explicit") + xlab("Explicit") + ylab("Number of songs")
ggsave('images/stats/song_explicit.png')
```

#### Song Popularity
```{r}
ggplot(data = genius_data, aes(x=song_popularity)) +
  geom_histogram() + 
  ggtitle("Song Popularity") + xlab("Popularity") + ylab("Number of Songs")
ggsave('images/stats/song_popularity.png')
```

#### Song Features
```{r}
# feature_name <- feature_cols2[i]
#   feature_name_print <- str_replace_all(feature_name,"_"," ")
#   x_label <- strsplit(feature_name,"_")[[1]][2]
#   print(ggplot(data = genius_data, aes_string(x="ranking_3", y=feature_name, fill="ranking_3")) + geom_boxplot() + ggtitle(feature_name_print) + xlab("Ranking") + ylab(x_label)) + gg_global_theme + scale_fill_viridis_d() + theme(legend.position = "none")
#   ggsave(paste0('images/stats/', feature_name,'.png'))
  
for(i in 1:length(feature_cols2)){
  feature_name <- feature_cols2[i]
  feature_name_print <- str_replace_all(feature_name,"_"," ")
  x_label <- strsplit(feature_name,"_")[[1]][2]
  print(ggplot(data = genius_data, aes_string(x=feature_name)) + geom_histogram() + ggtitle(feature_name_print) + xlab(x_label) + ylab("Number of Songs")) + gg_global_theme
  ggsave(paste0('images/stats/all/', feature_name,'.png'))
}
```
```{r}
feature_cols2 <- feature_cols2[! feature_cols2 %in% c("song_key", "song_mode")]
genius_data$song_duration <- genius_data$song_duration/60000
genius_data$ranking_3 <- as.factor(genius_data$ranking_3)
# temp <- genius_data[,c(feature_cols2,"ranking_3")]
temp <- melt(genius_data[,c(feature_cols2,"ranking_3")], id.vars = "ranking_3")
# ggplot(data = temp, aes(x=variable, y=value)) + geom_boxplot()

ggplot(data = temp, aes(x=variable, y=value)) + 
             geom_boxplot(aes(fill=ranking_3)) + facet_wrap( ~ variable, scales="free")
ggsave('images/all_variables.png')

ggplot(data = temp, aes(x=variable, y=value)) + 
             geom_boxplot() + facet_wrap( ~ variable, scales="free")
ggsave('images/variables.png')
```

